version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - mynetwork
    ports:
      - "5001:5001"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge